package vspackage.RemoteMethodApp.RemoteMethodPackage;


/**
* RemoteMethodApp/RemoteMethodPackage/AccessDeniedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/vanduong/Desktop/Concordia University/Courses/Distributed Systems/workspace/Corba/src/RemoteMethod.idl
* Thursday, July 11, 2019 3:51:30 PM EDT
*/

public final class AccessDeniedException extends org.omg.CORBA.UserException
{
  public String exceptReason = null;

  public AccessDeniedException ()
  {
    super(AccessDeniedExceptionHelper.id());
  } // ctor

  public AccessDeniedException (String _exceptReason)
  {
    super(AccessDeniedExceptionHelper.id());
    exceptReason = _exceptReason;
  } // ctor


  public AccessDeniedException (String $reason, String _exceptReason)
  {
    super(AccessDeniedExceptionHelper.id() + "  " + $reason);
    exceptReason = _exceptReason;
  } // ctor

} // class AccessDeniedException
