package vspackage.RemoteMethodApp.RemoteMethodPackage;


/**
* RemoteMethodApp/RemoteMethodPackage/ClassNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/vanduong/Desktop/Concordia University/Courses/Distributed Systems/workspace/Corba/src/RemoteMethod.idl
* Thursday, July 11, 2019 3:51:30 PM EDT
*/

public final class ClassNotFoundException extends org.omg.CORBA.UserException
{
  public String exceptReason = null;

  public ClassNotFoundException ()
  {
    super(ClassNotFoundExceptionHelper.id());
  } // ctor

  public ClassNotFoundException (String _exceptReason)
  {
    super(ClassNotFoundExceptionHelper.id());
    exceptReason = _exceptReason;
  } // ctor


  public ClassNotFoundException (String $reason, String _exceptReason)
  {
    super(ClassNotFoundExceptionHelper.id() + "  " + $reason);
    exceptReason = _exceptReason;
  } // ctor

} // class ClassNotFoundException
