package vspackage.RemoteMethodApp.RemoteMethodPackage;


/**
* RemoteMethodApp/RemoteMethodPackage/IllegalArgumentException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/vanduong/Desktop/Concordia University/Courses/Distributed Systems/workspace/Corba/src/RemoteMethod.idl
* Thursday, July 11, 2019 3:51:30 PM EDT
*/

public final class IllegalArgumentException extends org.omg.CORBA.UserException
{
  public String exceptReason = null;

  public IllegalArgumentException ()
  {
    super(IllegalArgumentExceptionHelper.id());
  } // ctor

  public IllegalArgumentException (String _exceptReason)
  {
    super(IllegalArgumentExceptionHelper.id());
    exceptReason = _exceptReason;
  } // ctor


  public IllegalArgumentException (String $reason, String _exceptReason)
  {
    super(IllegalArgumentExceptionHelper.id() + "  " + $reason);
    exceptReason = _exceptReason;
  } // ctor

} // class IllegalArgumentException
