package vspackage.RemoteMethodApp.RemoteMethodPackage;


/**
* RemoteMethodApp/RemoteMethodPackage/NoSuchFieldException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/vanduong/Desktop/Concordia University/Courses/Distributed Systems/workspace/Corba/src/RemoteMethod.idl
* Thursday, July 11, 2019 3:51:30 PM EDT
*/

public final class NoSuchFieldException extends org.omg.CORBA.UserException
{
  public String exceptReason = null;

  public NoSuchFieldException ()
  {
    super(NoSuchFieldExceptionHelper.id());
  } // ctor

  public NoSuchFieldException (String _exceptReason)
  {
    super(NoSuchFieldExceptionHelper.id());
    exceptReason = _exceptReason;
  } // ctor


  public NoSuchFieldException (String $reason, String _exceptReason)
  {
    super(NoSuchFieldExceptionHelper.id() + "  " + $reason);
    exceptReason = _exceptReason;
  } // ctor

} // class NoSuchFieldException
