package vspackage.RemoteMethodApp.RemoteMethodPackage;


/**
* RemoteMethodApp/RemoteMethodPackage/SecurityException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/vanduong/Desktop/Concordia University/Courses/Distributed Systems/workspace/Corba/src/RemoteMethod.idl
* Thursday, July 11, 2019 3:51:30 PM EDT
*/

public final class SecurityException extends org.omg.CORBA.UserException
{
  public String exceptReason = null;

  public SecurityException ()
  {
    super(SecurityExceptionHelper.id());
  } // ctor

  public SecurityException (String _exceptReason)
  {
    super(SecurityExceptionHelper.id());
    exceptReason = _exceptReason;
  } // ctor


  public SecurityException (String $reason, String _exceptReason)
  {
    super(SecurityExceptionHelper.id() + "  " + $reason);
    exceptReason = _exceptReason;
  } // ctor

} // class SecurityException
