package aspackage.OperationsApp;

/**
* OperationsApp/DEMSOperationsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operation.idl
* Wednesday, July 3, 2019 7:46:13 PM EDT
*/

public final class DEMSOperationsHolder implements org.omg.CORBA.portable.Streamable
{
  public aspackage.OperationsApp.DEMSOperations value = null;

  public DEMSOperationsHolder ()
  {
  }

  public DEMSOperationsHolder (aspackage.OperationsApp.DEMSOperations initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = aspackage.OperationsApp.DEMSOperationsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
	  aspackage.OperationsApp.DEMSOperationsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return aspackage.OperationsApp.DEMSOperationsHelper.type ();
  }

}
