package aspackage.OperationsApp;


/**
* OperationsApp/DEMSOperationsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operation.idl
* Wednesday, July 3, 2019 7:46:13 PM EDT
*/

public interface DEMSOperationsOperations 
{
  String addEvent (String eventId, String eventType, int bookingCapacity);
  String bookEvent (String customerId, String eventId, String eventType);
  String getBookingSchedule (String customerId);
  String cancelEvent (String customerId, String eventId, String eventType);
  String removeEvent (String eventId, String eventType);
  String listEventAvailability (String eventType);
  String swapEvent (String customerID, String newEventID, String newEventType, String oldEventID, String oldEventType);
  void shutdown ();
} // interface DEMSOperationsOperations
