package aspackage.OperationsApp;


/**
* OperationsApp/DEMSOperationsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operation.idl
* Wednesday, July 3, 2019 7:46:13 PM EDT
*/

abstract public class DEMSOperationsHelper
{
  private static String  _id = "IDL:OperationsApp/DEMSOperations:1.0";

  public static void insert (org.omg.CORBA.Any a, aspackage.OperationsApp.DEMSOperations that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static aspackage.OperationsApp.DEMSOperations extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (aspackage.OperationsApp.DEMSOperationsHelper.id (), "DEMSOperations");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static aspackage.OperationsApp.DEMSOperations read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DEMSOperationsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, aspackage.OperationsApp.DEMSOperations value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static aspackage.OperationsApp.DEMSOperations narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof aspackage.OperationsApp.DEMSOperations)
      return (aspackage.OperationsApp.DEMSOperations)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      aspackage.OperationsApp._DEMSOperationsStub stub = new aspackage.OperationsApp._DEMSOperationsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static aspackage.OperationsApp.DEMSOperations unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof aspackage.OperationsApp.DEMSOperations)
      return (aspackage.OperationsApp.DEMSOperations)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      aspackage.OperationsApp._DEMSOperationsStub stub = new aspackage.OperationsApp._DEMSOperationsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
