package aspackage.OperationsApp;


/**
* OperationsApp/DEMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operation.idl
* Wednesday, July 3, 2019 7:46:13 PM EDT
*/

public interface DEMSOperations extends DEMSOperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DEMSOperations
