package vspackage.RemoteMethodApp;


/**
* RemoteMethodApp/_RemoteMethodStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/vanduong/Desktop/Concordia University/Courses/Distributed Systems/workspace/Corba/src/RemoteMethod.idl
* Thursday, July 11, 2019 3:51:30 PM EDT
*/

public class _RemoteMethodStub extends org.omg.CORBA.portable.ObjectImpl implements vspackage.RemoteMethodApp.RemoteMethod
{

  public String addEvent (String eventID, String eventType, int bookingCapacity) throws vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteException, vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedException, vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundException, vspackage.RemoteMethodApp.RemoteMethodPackage.IOException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addEvent", true);
                $out.write_string (eventID);
                $out.write_string (eventType);
                $out.write_long (bookingCapacity);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/RemoteException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/AccessDeniedException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/ClassNotFoundException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/IOException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.IOExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return addEvent (eventID, eventType, bookingCapacity        );
            } finally {
                _releaseReply ($in);
            }
  } // addEvent

  public String removeEvent (String eventID, String eventType) throws vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteException, vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedException, vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundException, vspackage.RemoteMethodApp.RemoteMethodPackage.SecurityException, vspackage.RemoteMethodApp.RemoteMethodPackage.IOException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("removeEvent", true);
                $out.write_string (eventID);
                $out.write_string (eventType);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/RemoteException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/AccessDeniedException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/ClassNotFoundException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/SecurityException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.SecurityExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/IOException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.IOExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return removeEvent (eventID, eventType        );
            } finally {
                _releaseReply ($in);
            }
  } // removeEvent

  public String listEventAvailability (String eventType) throws vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteException, vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedException, vspackage.RemoteMethodApp.RemoteMethodPackage.IOException, vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundException, vspackage.RemoteMethodApp.RemoteMethodPackage.NoSuchFieldException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listEventAvailability", true);
                $out.write_string (eventType);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/RemoteException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/AccessDeniedException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/IOException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.IOExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/ClassNotFoundException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/NoSuchFieldException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.NoSuchFieldExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listEventAvailability (eventType        );
            } finally {
                _releaseReply ($in);
            }
  } // listEventAvailability

  public String bookEvent (String customerID, String eventID, String eventType) throws vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteException, vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedException, vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundException, vspackage.RemoteMethodApp.RemoteMethodPackage.IllegalArgumentException, vspackage.RemoteMethodApp.RemoteMethodPackage.IOException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("bookEvent", true);
                $out.write_string (customerID);
                $out.write_string (eventID);
                $out.write_string (eventType);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/RemoteException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/AccessDeniedException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/ClassNotFoundException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/IllegalArgumentException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.IllegalArgumentExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/IOException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.IOExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return bookEvent (customerID, eventID, eventType        );
            } finally {
                _releaseReply ($in);
            }
  } // bookEvent

  public String getBookingSchedule (String customerID) throws vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteException, vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedException, vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundException, vspackage.RemoteMethodApp.RemoteMethodPackage.IOException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getBookingSchedule", true);
                $out.write_string (customerID);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/RemoteException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/AccessDeniedException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/ClassNotFoundException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/IOException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.IOExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getBookingSchedule (customerID        );
            } finally {
                _releaseReply ($in);
            }
  } // getBookingSchedule

  public String cancelEvent (String customerID, String eventID, String eventType) throws vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteException, vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedException, vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundException, vspackage.RemoteMethodApp.RemoteMethodPackage.IOException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cancelEvent", true);
                $out.write_string (customerID);
                $out.write_string (eventID);
                $out.write_string (eventType);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/RemoteException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/AccessDeniedException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/ClassNotFoundException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/IOException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.IOExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return cancelEvent (customerID, eventID, eventType        );
            } finally {
                _releaseReply ($in);
            }
  } // cancelEvent

  public String swapEvent (String customerID, String newEventID, String newEventType, String oldEventID, String oldEventType) throws vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteException, vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedException, vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundException, vspackage.RemoteMethodApp.RemoteMethodPackage.IOException, vspackage.RemoteMethodApp.RemoteMethodPackage.NoSuchFieldException, vspackage.RemoteMethodApp.RemoteMethodPackage.IllegalArgumentException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("swapEvent", true);
                $out.write_string (customerID);
                $out.write_string (newEventID);
                $out.write_string (newEventType);
                $out.write_string (oldEventID);
                $out.write_string (oldEventType);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/RemoteException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/AccessDeniedException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/ClassNotFoundException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/IOException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.IOExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/NoSuchFieldException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.NoSuchFieldExceptionHelper.read ($in);
                else if (_id.equals ("IDL:RemoteMethodApp/RemoteMethod/IllegalArgumentException:1.0"))
                    throw vspackage.RemoteMethodApp.RemoteMethodPackage.IllegalArgumentExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return swapEvent (customerID, newEventID, newEventType, oldEventID, oldEventType        );
            } finally {
                _releaseReply ($in);
            }
  } // swapEvent

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:RemoteMethodApp/RemoteMethod:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _RemoteMethodStub
