package vspackage.RemoteMethodApp;

/**
* RemoteMethodApp/RemoteMethodHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/vanduong/Desktop/Concordia University/Courses/Distributed Systems/workspace/Corba/src/RemoteMethod.idl
* Thursday, July 11, 2019 3:51:30 PM EDT
*/

public final class RemoteMethodHolder implements org.omg.CORBA.portable.Streamable
{
  public vspackage.RemoteMethodApp.RemoteMethod value = null;

  public RemoteMethodHolder ()
  {
  }

  public RemoteMethodHolder (vspackage.RemoteMethodApp.RemoteMethod initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = vspackage.RemoteMethodApp.RemoteMethodHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
	  vspackage.RemoteMethodApp.RemoteMethodHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return vspackage.RemoteMethodApp.RemoteMethodHelper.type ();
  }

}
