package vspackage.RemoteMethodApp;


/**
* RemoteMethodApp/RemoteMethodHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/vanduong/Desktop/Concordia University/Courses/Distributed Systems/workspace/Corba/src/RemoteMethod.idl
* Thursday, July 11, 2019 3:51:30 PM EDT
*/

abstract public class RemoteMethodHelper
{
  private static String  _id = "IDL:RemoteMethodApp/RemoteMethod:1.0";

  public static void insert (org.omg.CORBA.Any a, vspackage.RemoteMethodApp.RemoteMethod that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static vspackage.RemoteMethodApp.RemoteMethod extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (vspackage.RemoteMethodApp.RemoteMethodHelper.id (), "RemoteMethod");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static vspackage.RemoteMethodApp.RemoteMethod read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RemoteMethodStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, vspackage.RemoteMethodApp.RemoteMethod value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static vspackage.RemoteMethodApp.RemoteMethod narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof vspackage.RemoteMethodApp.RemoteMethod)
      return (vspackage.RemoteMethodApp.RemoteMethod)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      vspackage.RemoteMethodApp._RemoteMethodStub stub = new vspackage.RemoteMethodApp._RemoteMethodStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static vspackage.RemoteMethodApp.RemoteMethod unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof vspackage.RemoteMethodApp.RemoteMethod)
      return (vspackage.RemoteMethodApp.RemoteMethod)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      vspackage.RemoteMethodApp._RemoteMethodStub stub = new vspackage.RemoteMethodApp._RemoteMethodStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
