package vspackage.RemoteMethodApp;


/**
* RemoteMethodApp/RemoteMethodOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/vanduong/Desktop/Concordia University/Courses/Distributed Systems/workspace/Corba/src/RemoteMethod.idl
* Thursday, July 11, 2019 3:51:30 PM EDT
*/

public interface RemoteMethodOperations 
{
  String addEvent (String eventID, String eventType, int bookingCapacity) throws vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteException, vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedException, vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundException, vspackage.RemoteMethodApp.RemoteMethodPackage.IOException;
  String removeEvent (String eventID, String eventType) throws vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteException, vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedException, vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundException, vspackage.RemoteMethodApp.RemoteMethodPackage.SecurityException, vspackage.RemoteMethodApp.RemoteMethodPackage.IOException;
  String listEventAvailability (String eventType) throws vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteException, vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedException, vspackage.RemoteMethodApp.RemoteMethodPackage.IOException, vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundException, vspackage.RemoteMethodApp.RemoteMethodPackage.NoSuchFieldException;
  String bookEvent (String customerID, String eventID, String eventType) throws vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteException, vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedException, vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundException, vspackage.RemoteMethodApp.RemoteMethodPackage.IllegalArgumentException, vspackage.RemoteMethodApp.RemoteMethodPackage.IOException;
  String getBookingSchedule (String customerID) throws vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteException, vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedException, vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundException, vspackage.RemoteMethodApp.RemoteMethodPackage.IOException;
  String cancelEvent (String customerID, String eventID, String eventType) throws vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteException, vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedException, vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundException, vspackage.RemoteMethodApp.RemoteMethodPackage.IOException;
  String swapEvent (String customerID, String newEventID, String newEventType, String oldEventID, String oldEventType) throws vspackage.RemoteMethodApp.RemoteMethodPackage.RemoteException, vspackage.RemoteMethodApp.RemoteMethodPackage.AccessDeniedException, vspackage.RemoteMethodApp.RemoteMethodPackage.ClassNotFoundException, vspackage.RemoteMethodApp.RemoteMethodPackage.IOException, vspackage.RemoteMethodApp.RemoteMethodPackage.NoSuchFieldException, vspackage.RemoteMethodApp.RemoteMethodPackage.IllegalArgumentException;
} // interface RemoteMethodOperations
