package FEApp;


/**
* FEApp/FEMethodOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/sandeepchowdaryannabathuni/eclipse-workspace/distributed_project/src/FEidl.idl
* Thursday, July 18, 2019 5:43:48 o'clock PM EDT
*/

public interface FEMethodOperations 
{
  String addEvent (String eventID, String eventType, int bookingCapacity);
  String removeEvent (String eventID, String eventType);
  String listEventAvailability (String eventType);
  String bookEvent (String customerID, String eventID, String eventType);
  String getBookingSchedule (String customerID);
  String cancelEvent (String customerID, String eventID, String eventType);
  String swapEvent (String customerID, String newEventID, String newEventType, String oldEventID, String oldEventType);
} // interface FEMethodOperations
