package FEApp;


/**
* FEApp/FEMethod.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/sandeepchowdaryannabathuni/eclipse-workspace/distributed_project/src/FEidl.idl
* Thursday, July 18, 2019 5:43:48 o'clock PM EDT
*/

public interface FEMethod extends FEMethodOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FEMethod
